### PR TITLE
fix attempt to index a number value on directive processing

### LINKED ISSUE #2: attempt to index a number value on directive processing
```
tarantool> require('luagraphqlparser').parse('fragment X on Y\n@foo\n{ name }')
---
- error: attempt to index a number value
...
```

Reported by @Totktonada

### PR DESCRIPTION
**Pull request by olegrok**
Closes #2

### CODE REVIEW

File: luagraphqlparser/lib.c [hunk 1]
```diff
@@ -650,12 +650,26 @@ visit_fragment_definition(const struct GraphQLAstFragmentDefinition *def, void *
 static void
```
Comment (ligurio) [inline luagraphqlparser/lib.c:650]: Typo in commit message header (ttempt -> attempt)

Comment (Totktonada) [reply luagraphqlparser/lib.c:650]: Seems resolved.

**Review by Totktonada — APPROVED** [review]
LGTM.

Thanks!
